### ISSUE TITLE
Probe registered and worked, then stopped

### ISSUE THREAD

**Issue by 0xE1** [Jamesits/docker-ripe-atlas#11]
Probe registered and worked for some time, but stopped in few hours and haven't been online for 19+ hours.

It has this repeated many times:
```
{ "name": "lo", "bytes_recv": 1144069, "pkt_recv": 12263, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 1144069, "pkt_sent": 12263, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }, { "name": "tunl0", "bytes_recv": 0, "pkt_recv": 0, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 0, "pkt_sent": 0, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }, { "name": "gre0", "bytes_recv": 0, "pkt_recv": 0, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 0, "pkt_sent": 0, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }, { "name": "gretap0", "bytes_recv": 0, "pkt_recv": 0, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 0, "pkt_sent": 0, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }RESULT 9006 done 1615238073 000000000000 no reginit.vol start registeration
/var/atlas-probe/status/reginit.vol does not exist try new reg
[warn] Unable to parse nameserver address 8.8.4.4
[warn] Unable to parse nameserver address 2003:c2:3f04:d100:<redacted>
evping: bad address 'U181146.Hd99726584cb21a35.sos.atlas.ripe.net'
evping_ops.init failed

Ping failed


g
ATLAS registeration starting
registeration info is still valid till 1615239686, now 1615238073
check cached controller info from previous registeration

NO cached controller info. NO REMOTE port info

Do a controller INIT

Controller init -p 443 atlas@ctr-fsn01.atlas.ripe.net INIT

255 controller INIT exit with error

condmv: not moving, destination '/var/atlas-probe/data/out/v6addr.txt' exists
condmv: not moving, destination '/var/atlas-probe/data/out/simpleping' exists
```

p.s. I changed /etc/resolv.conf with google dns to see if it will fix ipv6 related issues, no dice but it worked for a while.
This is on UnRaid.

**Comment by ALEXSANPEDRO** [comment]
Can you help me, how you resolve this, ive register a probe but it inactive in cabinet. in container logs i see this 
g

ATLAS registration starting

registration info is still valid till 1680103250, now 1680102959

check cached controller info from previous registration

NO cached controller info. NO REMOTE port info

Do a controller INIT

Controller init -p  443 atlas@ctr-fsn02.atlas.ripe.net  INIT

255 controller INIT exit with error

condmv: not moving, destination '/var/atlas-probe/data/out/v6addr.txt' exists

condmv: not moving, destination '/var/atlas-probe/data/out/simpleping' exists

 { "name": "lo", "bytes_recv": 18244, "pkt_recv": 200, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 18244, "pkt_sent": 200, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }, { "name": "eth0", "bytes_recv": 16244, "pkt_recv": 67, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 8610, "pkt_sent": 41, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }RESULT 9006 done 1680103139 0242ac150002 no reginit.vol start registration

/var/atlas-probe/status/reginit.vol does not exist try new reg

evping: bad address 'U61288.H1ff937365c720f0b.sos.atlas.ripe.net'

evping_ops.init failed

Ping failed
