### ISSUE TITLE
why need SYS_ADMIN,NET_RAW,CHOWN ?

### ISSUE THREAD

**Issue by douniwan5788** [Jamesits/docker-ripe-atlas#13]

**Comment by Jamesits** [comment]
CHOWN is used [here](https://github.com/Jamesits/docker-ripe-atlas/blob/5b7a691b5757a19b222fd00e97034099d63c4d9d/entrypoint.sh#L9) to automatically create directories required by the atlas software.

The other 2 permissions are used by the atlas software itself at the time I wrote the doc. You can try disabling them and see if it still works. I'll always welcome contribution to the doc.

**Comment by Jamesits** [comment]
Closing due to lack of response - If you have further questions, please comment below.
