### ISSUE TITLE
ARM CI seems to have been broken for a few weeks

### ISSUE THREAD

**Issue by Tugzrida** [Jamesits/docker-ripe-atlas#14]
The [Azure logs](https://dev.azure.com/nekomimiswitch/General/_build/results?buildId=12413&view=logs&j=07f4470b-245e-563e-8b22-e6858f24de46&t=07e34aed-7c7f-53d4-725a-83fc62479c7e&l=12) seem to indicate that docker isn't running on the CI machine? Not sure what that indicates.

**Comment by Jamesits** [comment]
Docker daemon on the CI machine failed to start due to too many containers in the database. Temporary fix has been applied and I can see it is taking up builds again. 

Thanks for the heads-up!
