### ISSUE TITLE
docker log format

### ISSUE THREAD

**Issue by netahoy** [Jamesits/docker-ripe-atlas#16]
So adding just `--log-opt max-size=10m` in the docker (20.10.11) command line throws error like 
_docker: Error response from daemon: unknown log opt 'max-size' for journald log driver._
I have been running these command on my Pi with log type defined like every time for last  ...
 `--log-driver json-file --log-opt max-size=5m`

Does this call for an update of the reference command line?

Anyhow keep up the good work...

**Comment by Jamesits** [comment]
Nice catch.

**Comment by netahoy** [comment]
Thanks for updating the reference command line at git repo, for the novice the same needs to be updated at https://hub.docker.com/r/jamesits/ripe-atlas

**Comment by Jamesits** [comment]
@netahoy Thank you for pointing out this! I've removed most of the readme at the Docker Hub and left a link to this repo since the readme will not be auto updated anymore...
