### ISSUE TITLE
IPv4 connectivity not working

### ISSUE THREAD

**Issue by daryll-swer** [Jamesits/docker-ripe-atlas#17]
So I have Pi that has a public IPv4/IPv6 address on the WAN interface (eth0), Docker itself has a routed /64 available for its use and the containers get a /128 GUA that's publicly reachable.

So the problem is, my Ripe Atlas Probe has IPv6 connectivity without a problem, but IPv4 does not work for some reason. Docker is correctly NATting by masquerading to the public IP of my Pi's WAN interface, but when checking on the RIPE Website, the Probe has a private IPv4 address from Docker, but no public access to the IPv4 world. Any ideas on what's the issue here?

- Pi OS Lite 64-Bit
Used the following to spin up the container
> docker run --detach --restart=always --log-opt max-size=10m \
    --cpus=1 --memory=64m --memory-reservation=64m \
    --cap-add=SYS_ADMIN --cap-add=NET_RAW --cap-add=CHOWN \
    --mount type=tmpfs,destination=/var/atlasdata,tmpfs-size=64M \
    -v /var/atlas-probe/etc:/var/atlas-probe/etc \
    -v /var/atlas-probe/status:/var/atlas-probe/status \
    -e RXTXRPT=yes \
    --name ripe-atlas --hostname "$(hostname --fqdn)" \
    jamesits/ripe-atlas:latest-armv7l

**Comment by Jamesits** [comment]
I have no idea. Maybe try `docker exec -it ripe-atlas ping 8.8.8.8` to see if IPv4 is actually reachable?

**Comment by daryll-swer** [comment]
```
$ docker exec -it ripe-atlas ping 8.8.8.8
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "ping": executable file not found in $PATH: unknown
```

**Comment by daryll-swer** [comment]
Not sure how or why, but IPv4 now seems to be working on the RIPE Website. Closing this until it shows up again.
