### ISSUE TITLE
Can't register software probe

### ISSUE THREAD

**Issue by MadGhigno** [Jamesits/docker-ripe-atlas#21]
Installed the software probe open image and trying to register the probe with public key return the following registration error:

- "The public key does not match our regular expression for this keytype"

They key is the on present in the direcroty: /var/atlas-probe

Tried to generate a new one but nothing happens

**Comment by Jamesits** [comment]
Please confirm that your key is a RSA 2048 or 4096-bit key that starts with `ssh-rsa`?

**Comment by MadGhigno** [comment]
It's the one present in the docker image. I tried to create a new one with:

ssh-keygen -t rsa -b 4096

but I get the same error

**Comment by Jamesits** [comment]
Just to make sure, you submitted the public key (the one with a single line of text) right?

**Comment by MadGhigno** [comment]
yes, it generates two keys public (id_rsa.pub) and private (id_rsa). I used the id_rsa.pub

**Comment by Jamesits** [comment]
This seems weird, I think it's a bug at the RIPE website's side. I've checked the doc and there are no changes about the public key format...

**Comment by Jamesits** [comment]
The container generates the key using `ssh-keygen -t rsa -b 2048` ([reference](https://github.com/RIPE-NCC/ripe-atlas-software-probe/blob/67b0736887d33d1c42557e7c7694cbd4e5d8e6ee/bin/arch/debian-sw-probe/debian-sw-probe-ATLAS.sh#L68)) (and you can even replace it with your own generated key), so there is no need to retry that. If RIPE website doesn't accept this format, then either their website or their documentation has some problem. I'd suggest asking on RIPE Atlas' mailing list.
