### ISSUE TITLE
Errors after new instance probe, cant register. 

### ISSUE THREAD

**Issue by ALEXSANPEDRO** [Jamesits/docker-ripe-atlas#23]
Ive installed probe, try to register. Registration works well, but in logs of container i see this:
ATLAS registration starting
g

ATLAS registration starting

REASON_FOR_REGISTRATION NEW NO previous state files

REGHOSTS reg03.atlas.ripe.net 193.0.19.246 2001:67c:2e8:11::c100:13f6 reg04.atlas.ripe.net 193.0.19.247 2001:67c:2e8:11::c100:13f7

ssh -p 443 atlas@2001:67c:2e8:11::c100:13f7 INIT

255  REGINIT exit with error

condmv: not moving, destination '/var/atlas-probe/data/out/v6addr.txt' exists

condmv: not moving, destination '/var/atlas-probe/data/out/simpleping' exists

 { "name": "lo", "bytes_recv": 3676, "pkt_recv": 36, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 3676, "pkt_sent": 36, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }, { "name": "eth0", "bytes_recv": 13720, "pkt_recv": 55, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 6778, "pkt_sent": 29, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 }RESULT 9006 done 1680111364 0242ac150002 no reginit.vol start registration

/var/atlas-probe/status/reginit.vol does not exist try new reg

evping: bad address 'U69513.Hb6b730724a11c42f.sos.atlas.ripe.net'

evping_ops.init failed

Ping failed

And it repeats in logs. probe in ripe have status - NEVER CONNECT. but when i register probe i recieve a mail that my probe registered. 

Where i wrong? before reinstalling my host system everyting works well, but now cant resolve this problem

**Comment by ALEXSANPEDRO** [comment]
> First try ping `reg03.atlas.ripe.net` with both IPv4 and IPv6 on your host and see if it works.

root@openmediavault:~# ping reg03.atlas.ripe.net
PING reg03.atlas.ripe.net (193.0.19.246) 56(84) bytes of data.
64 bytes from reg03.atlas.ripe.net (193.0.19.246): icmp_seq=1 ttl=57 time=46.2 ms
64 bytes from reg03.atlas.ripe.net (193.0.19.246): icmp_seq=2 ttl=57 time=46.0 ms
64 bytes from reg03.atlas.ripe.net (193.0.19.246): icmp_seq=3 ttl=57 time=46.0 ms
64 bytes from reg03.atlas.ripe.net (193.0.19.246): icmp_seq=4 ttl=57 time=46.0 ms
64 bytes from reg03.atlas.ripe.net (193.0.19.246): icmp_seq=5 ttl=57 time=46.1 ms
64 bytes from reg03.atlas.ripe.net (193.0.19.246): icmp_seq=6 ttl=57 time=46.1 ms
64 bytes from reg03.atlas.ripe.net (193.0.19.246): icmp_seq=7 ttl=57 time=46.0 ms

**Comment by ALEXSANPEDRO** [comment]
version: "2.0"

services:
  ripe-atlas:
    image: jamesits/ripe-atlas:latest
    restart: always
#  network_mode: 'host' - try add this line, but same result
    environment:
      RXTXRPT: "no"
    volumes:
      - "/srv/dev-disk-by-uuid-201d48fb-9acc-4ebd-ac77-4a48206a723a/dockerimg/atlas-probe/docker-ripe-atlas/etc:/var/atlas-probe/etc"
      - "/srv/dev-disk-by-uuid-201d48fb-9acc-4ebd-ac77-4a48206a723a/dockerimg/atlas-probe/docker-ripe-atlas/status:/var/atlas-probe/status"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_RAW
    mem_limit: "64000000000"
    mem_reservation: 64m
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: json-file
      options:
         max-size: 10m
    # security_opt:
    #   - seccomp:unconfined


I use your default compose file with my volumes

**Comment by D13410N3** [comment]
The same issue

**Comment by grapeslush** [comment]
Running into the same problem. Are there any identified solutions?

**Comment by Jamesits** [comment]
Which architecture are you guys using when having this problem?

**Comment by grapeslush** [comment]
@Jamesits I figured it out just now on my end. It was permissions for the ssh private key. They were too open so the key was being ignored. Set it to 400 and now it's working just fine.

I would image it's probably the same problem for the users above.

**Comment by D13410N3** [comment]
@Jamesits As @grapeslush said, yes, this really was an issue - incorrect chmod on the private key. When I had fixed it, everything started working properly

**Comment by Jamesits** [comment]
I'm glad that the issue have been found. Thank @grapeslush !
