### ISSUE TITLE
Errors after getting the latest image

### ISSUE THREAD

**Issue by amartins** [Jamesits/docker-ripe-atlas#25]
I enabled auto-update in my Docker container and observed that my probe got disconnected. It seems that something is broken because I'm encountering errors related to libcrypto.so.1.1. Here are the relevant logs for reference:

/usr/local/atlas/bb-13.3/bin/rptaddrs: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/bin/atlas: 297: [: -gt: unexpected operator
cat: /var/atlas-probe/run/perd-main.pid.vol: No such file or directory
cat: /var/atlas-probe/run/perd-7.pid.vol: No such file or directory
cat: /var/atlas-probe/run/eooqd.pid.vol: No such file or directory
RESULT 9006 done 1686636436 0242ac110005 no reginit.vol start registration
/var/atlas-probe/status/reginit.vol does not exist try new reg
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/evping: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
Ping failed

g
ATLAS registration starting
REREG_TIMER 1686603295 expired now is 1686636436
REREG_TIMER_EXPIRED  go re register REREG_TIMER 1  , now is 1686636436  
/usr/local/atlas/bb-13.3/bin/rchoose: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
REGHOSTS reg03.atlas.ripe.net 193.0.19.246 2001:67c:2e8:11::c100:13f6 reg04.atlas.ripe.net 193.0.19.247 2001:67c:2e8:11::c100:13f7
ssh -p 443 atlas@ INIT
255  REGINIT exit with error
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptaddrs: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/bin/atlas: 297: [: -gt: unexpected operator
cat: /var/atlas-probe/run/perd-main.pid.vol: No such file or directory
cat: /var/atlas-probe/run/perd-7.pid.vol: No such file or directory
cat: /var/atlas-probe/run/eooqd.pid.vol: No such file or directory
RESULT 9006 done 1686636616 0242ac110005 no reginit.vol start registration
/var/atlas-probe/status/reginit.vol does not exist try new reg
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/evping: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
Ping failed

g
ATLAS registration starting
REREG_TIMER 1686603295 expired now is 1686636616
REREG_TIMER_EXPIRED  go re register REREG_TIMER 1  , now is 1686636616  
/usr/local/atlas/bb-13.3/bin/rchoose: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
REGHOSTS reg03.atlas.ripe.net 193.0.19.246 2001:67c:2e8:11::c100:13f6 reg04.atlas.ripe.net 193.0.19.247 2001:67c:2e8:11::c100:13f7
ssh -p 443 atlas@ INIT
255  REGINIT exit with error
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptaddrs: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/bin/atlas: 297: [: -gt: unexpected operator
cat: /var/atlas-probe/run/perd-main.pid.vol: No such file or directory
cat: /var/atlas-probe/run/perd-7.pid.vol: No such file or directory
cat: /var/atlas-probe/run/eooqd.pid.vol: No such file or directory
RESULT 9006 done 1686636796 0242ac110005 no reginit.vol start registration
/var/atlas-probe/status/reginit.vol does not exist try new reg
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/evping: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
Ping failed

g
ATLAS registration starting
REREG_TIMER 1686603295 expired now is 1686636796
REREG_TIMER_EXPIRED  go re register REREG_TIMER 1  , now is 1686636796  
/usr/local/atlas/bb-13.3/bin/rchoose: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
REGHOSTS reg03.atlas.ripe.net 193.0.19.246 2001:67c:2e8:11::c100:13f6 reg04.atlas.ripe.net 193.0.19.247 2001:67c:2e8:11::c100:13f7
ssh -p 443 atlas@ INIT
255  REGINIT exit with error
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptaddrs: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/bin/atlas: 297: [: -gt: unexpected operator
cat: /var/atlas-probe/run/perd-main.pid.vol: No such file or directory
cat: /var/atlas-probe/run/perd-7.pid.vol: No such file or directory
cat: /var/atlas-probe/run/eooqd.pid.vol: No such file or directory
RESULT 9006 done 1686636976 0242ac110005 no reginit.vol start registration
/var/atlas-probe/status/reginit.vol does not exist try new reg
/usr/local/atlas/bb-13.3/bin/onlyuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/evping: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
Ping failed

g
ATLAS registration starting
REREG_TIMER 1686603295 expired now is 1686636976
REREG_TIMER_EXPIRED  go re register REREG_TIMER 1  , now is 1686636976  
/usr/local/atlas/bb-13.3/bin/rchoose: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
REGHOSTS reg03.atlas.ripe.net 193.0.19.246 2001:67c:2e8:11::c100:13f6 reg04.atlas.ripe.net 193.0.19.247 2001:67c:2e8:11::c100:13f7
ssh -p 443 atlas@ INIT
255  REGINIT exit with error
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rxtxrpt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptaddrs: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/rptuptime: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/local/atlas/bb-13.3/bin/condmv: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

**Comment by Jamesits** [comment]
Please try out the latest image.

**Comment by alexdelprete** [comment]
> Please try out the latest image.

I had the same issue, last night watchtower upgraded the image and the probe was disconnected with same errors in the log as the OP.

I just pulled latest image and restarted, looks good now, except some `source: not found` errors in the log.

```
usermod: no changes
Option RXTXRPT="yes"
/usr/local/bin/atlas: 23: /usr/local/bin/atlas: source: not found
/usr/local/bin/atlas: 24: /usr/local/bin/atlas: source: not found
/usr/local/bin/atlas: 25: /usr/local/bin/atlas: source: not found
/usr/local/bin/atlas: 26: /usr/local/bin/atlas: source: not found
/usr/local/bin/atlas: 27: /usr/local/bin/atlas: source: not found
RESULT 9000 done 1686671643 0242ac130002 STARTING ATLAS system initialized (reboot count 0)
RESULT 9000 done 1686671643 0242ac130002 STARTING TELNETD LOCALLY
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.0.2  netmask 255.255.0.0  broadcast 172.19.255.255
        ether 02:42:ac:13:00:02  txqueuelen 0  (Ethernet)
        RX packets 1  bytes 342 (342.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

RESULT 9006 done 1686671644 0242ac130002 no reginit.vol start registration
/var/atlas-probe/status/reginit.vol does not exist try new reg
Ping failed
start reg
ATLAS registration starting
registration info is still valid till 1686674861, now 1686671644
check cached controller info from previous registration
Use cached controller info -R 53232 atlas@ctr-fsn02.atlas.ripe.net
initiating  KEEP connection to -R 53232 -p  443 ctr-fsn02.atlas.ripe.net
Moving reboot-count.txt
found KEEP ssh client running
condmv: not moving, destination '/var/atlas-probe/data/out/v6addr.txt' exists
condmv: not moving, destination '/var/atlas-probe/data/out/simpleping' exists
found KEEP ssh client running

```

**Comment by amartins** [comment]
> Please try out the latest image.

I've just pulled the latest image and I can confirm it's working. Thanks for your swift response.
