### ISSUE TITLE
setpriv error

### ISSUE THREAD

**Issue by cloud-erik** [Jamesits/docker-ripe-atlas#33]
Since the last update, the node has only repeated logs
`sermod: no changes
Option RXTXRPT=yes
setpriv: failed to execute ripe-atlas: No such file or directory`
and dont start up.
The update a few hours before the last one (about 22.08. GMT 18) already caused a connection loss to the Atlas network.
Would be great if someone has an idea how to get it working again.

As suggested, the container is automatically updated by Watchtower.

Would appreciate any help.
Erik

**Comment by Dreista** [comment]
Hmm, this is unlikely to happen if you are using the latest image. Could you confirm that you are using the current `jamesits/ripe-atlas:latest` image (not the previous reverted image with probe version 5090), and not manually overriding `CMD` (it should be `atlas` instead of `ripe-atlas`)?

The name of the executable were changed from `atlas` to `ripe-atlas` since version 5090.

**Comment by cloud-erik** [comment]
Thanks for rocket fast reply :-) @Dreista 
Yes its latest image, just pulled it a few minutes ago to be sure. (sha256:288a17d0882b98a43dac1c0391e34131e36fbea955c34dff1375a1a4ae5ba84a)

I am using the the Image from docker hub not building it local and dont overwritten CMD.

Here my compose for info:

`services:
  ripe-atlas:
    image: jamesits/ripe-atlas:latest
    restart: always
    environment:
      RXTXRPT: "yes"
    volumes:
      - "/var/atlas-probe/etc:/var/atlas-probe/etc"
      - "/var/atlas-probe/status:/var/atlas-probe/status"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_RAW
    mem_limit: "64000000000"
    mem_reservation: 64m
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
    logging:
      driver: json-file
      options:
         max-size: 10m
    healthcheck:
      test: find /var/atlas-probe/status/ -mmin -5 || exit
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    #network_mode: "host" # if possible, avoid double NAT
    # security_opt:
    #   - seccomp:unconfined
    networks:
       ipv6:
         ipv6_address: aaaa:bbbb:cccc:dddd::0001

networks:
  ipv6:
    external: true   `

**Comment by Dreista** [comment]
I cannot seem to reproduce the issue. May I ask if you can provide output of `docker inspect ripe-atlas` with sensitive data redacted?

**Comment by cloud-erik** [comment]
Thanks for your help and pointing in the right direction. I already saw that CMD is still "ripe-atlas" as you mentioned in your first post.

Please find inspect below:
`[
    {
        "Id": "74ee8662c862aec3b4a1d01523771d63503342d074752eff0268d41f25cff87c",
        "Created": "2024-08-24T08:17:34.836478332Z",
        "Path": "tini",
        "Args": [
            "--",
            "entrypoint.sh",
            "ripe-atlas"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 127,
            "Error": "",
            "StartedAt": "2024-08-24T09:00:33.166656569Z",
            "FinishedAt": "2024-08-24T09:00:34.373081038Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 0,
                "Log": []
            }
        },
        "Image": "sha256:288a17d0882b98a43dac1c0391e34131e36fbea955c34dff1375a1a4ae5ba84a",
        "ResolvConfPath": "/var/lib/docker/containers/74ee8662c862aec3b4a1d01523771d63503342d074752eff0268d41f25cff87c/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/74ee8662c862aec3b4a1d01523771d63503342d074752eff0268d41f25cff87c/hostname",
        "HostsPath": "/var/lib/docker/containers/74ee8662c862aec3b4a1d01523771d63503342d074752eff0268d41f25cff87c/hosts",
        "LogPath": "/var/lib/docker/containers/74ee8662c862aec3b4a1d01523771d63503342d074752eff0268d41f25cff87c/74ee8662c862aec3b4a1d01523771d63503342d074752eff0268d41f25cff87c-json.log",
        "Name": "/ripe_atlas_probe-ripe-atlas-1",
        "RestartCount": 51,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/atlas-probe/etc:/var/atlas-probe/etc:rw",
                "/var/atlas-probe/status:/var/atlas-probe/status:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-size": "10m"
                }
            },
            "NetworkMode": "1ea180b2fe32b43bccab20ea343626b5ab93ca6e061d2f1e7932424c6056847a",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": [
                "CHOWN",
                "SETUID",
                "SETGID",
                "DAC_OVERRIDE",
                "NET_RAW"
            ],
            "CapDrop": [
                "ALL"
            ],
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 64000000000,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 67108864,
            "MemorySwap": -1,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/b58a5451a1693689b6b92af5b443dfa0e43465aa7381e9769f41925213137a42-init/diff:/var/lib/docker/overlay2/64588faebcac9b5a11b91648bc7edab78ebe1d5e8594b5dc19c14e6a9f4b5b28/diff:/var/lib/docker/overlay2/cd0871b86d0b21e33d8922e718953cd12c6139950545f733aa6d724e516bbb1a/diff:/var/lib/docker/overlay2/d9517d5bfcc88de7d20ed7ccde5f971910c2d6e53c2479520c7bce965bc54aa8/diff:/var/lib/docker/overlay2/bd095f26a45f51c647867f48f07fec261139c867d8af4a92a0baa164cdfd5d58/diff:/var/lib/docker/overlay2/834b9cd59d3537e562869f10275d36154ca6ce84d51f57e757a95dfb401a92ee/diff:/var/lib/docker/overlay2/1ab0dadf57437c5edd80c1f160a50045f2797488796f26def3357325869d9b24/diff",
                "MergedDir": "/var/lib/docker/overlay2/b58a5451a1693689b6b92af5b443dfa0e43465aa7381e9769f41925213137a42/merged",
                "UpperDir": "/var/lib/docker/overlay2/b58a5451a1693689b6b92af5b443dfa0e43465aa7381e9769f41925213137a42/diff",
                "WorkDir": "/var/lib/docker/overlay2/b58a5451a1693689b6b92af5b443dfa0e43465aa7381e9769f41925213137a42/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/atlas-probe/etc",
                "Destination": "/var/atlas-probe/etc",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/atlas-probe/status",
                "Destination": "/var/atlas-probe/status",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "2d1ce871a9b1439eef4c9229f75a5950321c35a886fa59ab8838bea7da9d5f33",
                "Source": "/var/lib/docker/volumes/2d1ce871a9b1439eef4c9229f75a5950321c35a886fa59ab8838bea7da9d5f33/_data",
                "Destination": "/etc/ripe-atlas",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "64e5803b8fef37aa2df16b9458f2bf72c2ad1199a5b651e1a819605fea11cce0",
                "Source": "/var/lib/docker/volumes/64e5803b8fef37aa2df16b9458f2bf72c2ad1199a5b651e1a819605fea11cce0/_data",
                "Destination": "/run/ripe-atlas/status",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "8557a5d08e0b",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "RXTXRPT=yes",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "ripe-atlas"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "find /var/atlas-probe/status/ -mmin -5 || exit"
                ],
                "Interval": 60000000000,
                "Timeout": 10000000000,
                "StartPeriod": 60000000000,
                "Retries": 5
            },
            "Image": "jamesits/ripe-atlas:latest",
            "Volumes": {
                "/etc/ripe-atlas": {},
                "/run/ripe-atlas/status": {},
                "/var/atlas-probe/etc": {},
                "/var/atlas-probe/status": {}
            },
            "WorkingDir": "/etc/ripe-atlas",
            "Entrypoint": [
                "tini",
                "--",
                "entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.centurylinklabs.watchtower.enable": "true",
                "com.centurylinklabs.watchtower.monitor-only": "false",
                "com.docker.compose.config-hash": "2d0c5c1600d82aab31a58f583f1d3496ac9693801c40a6e00e612be6ee1d5494",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:a4e83b715d93c673f9c77fa648be2187d13c146f17c446110ab933f26f122c3c",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ripe_atlas_probe",
                "com.docker.compose.project.config_files": "/data/compose/68/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/data/compose/68",
                "com.docker.compose.replace": "4068cdd823dbd157568c53846e453181af8462b052d68360e79c75f33131f476",
                "com.docker.compose.service": "ripe-atlas",
                "com.docker.compose.version": "2.20.2",
                "image": "ripe-atlas",
                "maintainer": "dockerhub@public.swineson.me",
                "org.opencontainers.image.authors": "dockerhub@public.swineson.me",
                "org.opencontainers.image.title": "ripe-atlas",
                "traefik.enable": "false"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "24e82d635d3d66d6a602354774023dc100115463a98f9fecbfd7b9dc0a9aa742",
            "SandboxKey": "/var/run/docker/netns/24e82d635d3d",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "ipv6": {
                    "IPAMConfig": {
                        "IPv6Address": "xxxx"
                    },
                    "Links": null,
                    "Aliases": [
                        "ripe_atlas_probe-ripe-atlas-1",
                        "ripe-atlas",
                        "8557a5d08e0b",
                        "863e039f10cd",
                        "bb66fe5109ff",
                        "740f89f6bbf7",
                        "d53e77e4cbde",
                        "b81687e3b36d",
                        "7472d5f3b06d",
                        "2425e5e67df2",
                        "055e8f574f1c",
                        "0a077bed647c"
                    ],
                    "MacAddress": "",
                    "NetworkID": "1ea180b2fe32b43bccab20ea343626b5ab93ca6e061d2f1e7932424c6056847a",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "ripe_atlas_probe-ripe-atlas-1",
                        "ripe-atlas",
                        "8557a5d08e0b",
                        "863e039f10cd",
                        "bb66fe5109ff",
                        "740f89f6bbf7",
                        "d53e77e4cbde",
                        "b81687e3b36d",
                        "7472d5f3b06d",
                        "2425e5e67df2",
                        "055e8f574f1c",
                        "0a077bed647c",
                        "74ee8662c862"
                    ]
                }
            }
        }
    }
]
`

**Comment by Dreista** [comment]
Ahh, I see. So `CMD` somehow got stuck at `ripe-atlas` when image is updated. In this case, I would try completely removing that old container first:

```shell
docker container stop ripe-atlas
docker container rm ripe-atlas
```

And try compose again.
If that doesn't work, resetting docker may help.

**Comment by cloud-erik** [comment]
Thanks a lot @Dreista, That solved it already and was easier as expected :-)
