### ISSUE TITLE
Add option to override UID:GID of the atlas user

### ISSUE THREAD

**Issue by Vorsku** [Jamesits/docker-ripe-atlas#6]
Hi,

I'm trying to get this container running using persistent storage on an NFS share, but I keep getting the below error:
```
chown: changing ownership of '/var/atlas-probe/status': Operation not permitted
```

I see in the entrypoint.sh file that it chown's the directories with atlas:atlas, so I need to set the container's atlas:atlas UID/GID to 1000:100 which are the permissions on the NFS share, however I've tried using --user="1000:100" to no avail.

Here is my docker run command:
```
docker run --rm --name ripe-atlas --user="1000:100" --log-opt max-size=10m  --cap-add=SYS_ADMIN --cap-add=NET_RAW --cap-add=CHOWN --mount type=tmpfs,destination=/var/atlasdata,tmpfs-size=64M -v /nfs/docker/ripe/etc:/var/atlas-probe/etc -v /nfs/docker/ripe/status:/var/atlas-probe/status -e RXTXRPT=yes --hostname "$(hostname --fqdn)" jamesits/ripe-atlas:latest-armv7l
```

Thanks!

**Comment by Jamesits** [comment]
The `atlas` user is created in the atlas deb package so it is a little hard to change the UID/GID at runtime. I'd propose 2 options on your request:

1. I've provided 2 arguments to change the UID/GID during a `docker build` in https://github.com/Jamesits/docker-ripe-atlas/commit/6ac4f71fdfb442fe388ab12898bf746778e8e24e, and you can build your own image with any UID/GID you like.

2. Mount your own `/etc/passwd` file to the container to modify the UID/GID.

Let me know if any of these fit your use case.

**Comment by Vorsku** [comment]
@Jamesits thanks! Mounting a custom /etc/passwd amended the UID/GID but still gave me chown errors, so I'll try amending via docker build.

**Comment by Jamesits** [comment]
closing due to aging; if the problem consists, please request a re-open.
