### ISSUE TITLE
Error from docker logs

### ISSUE THREAD

**Issue by menghoumenghou** [Jamesits/docker-ripe-atlas#7]
![image](https://user-images.githubusercontent.com/20235458/97097634-bebad280-16ad-11eb-9078-359187e2b323.png)
I found the statistics of in/out traffic on RIPE probe panel is always zero so I looked into the logs of the docker image and found above message.
Could you please look into it and see what could be the reason ?

**Comment by Jamesits** [comment]
I don't think it is the docker images' fault; verify you have `RXTXRPT=yes` set up; if the problem is still happening, see https://github.com/RIPE-NCC/ripe-atlas-software-probe/issues/32

**Comment by menghoumenghou** [comment]
Thanks, I looked into the logs of the docker host and found below
![image](https://user-images.githubusercontent.com/20235458/97105409-6dcecc80-16f5-11eb-9ceb-cc844bf85af0.png)

It seems more like to be related to this one :
https://github.com/RIPE-NCC/ripe-atlas-software-probe/issues/49

**Comment by Jamesits** [comment]
Yes, this also happens on my instances...

**Comment by menghoumenghou** [comment]
I think this issue is resolved, it is related to the code of Atlas probe and it assumes IPv6 is enabled by default but apparently by default docker doesn't turn it on. I have added a comment under the Atlas Probe issue log.
 https://github.com/RIPE-NCC/ripe-atlas-software-probe/issues/49#issuecomment-717632266

**Comment by menghoumenghou** [comment]
I think now we can close the issue, hope the changes from Atlas probe will be merged to the next version of software probe.
